### ISSUE TITLE
Age Rating on Some Files

### ISSUE THREAD

**Issue by tapishdongre** [bunnykek/kuku-dl#10]
This is not urgent, you can solve this later when you have time,
![Kuku Error Special](https://github.com/user-attachments/assets/918bd0a2-54b6-4976-ac6a-f9e62f1d32b5)

Would you be able to load or try these links on your side? It is giving an age rating error. The ablums are:

All other normal albums are working, thus did not know what was special in these ones

NOT WORKING:

python kuku.py https://kukufm.com/show/ek-hote-sarovar  (error age rating) and Error Show

python kuku.py https://kukufm.com/show/varyavarchi-varat

python kuku.py https://kukufm.com/show/faster-fenechi-express-kamgiri

python kuku.py https://kukufm.com/show/tu-aani-me

python kuku.py https://kukufm.com/show/hasare-dukkha  (very big file size)

python kuku.py https://kukufm.com/show/indraneel  (sifi marathi)

**Comment by bunnykek** [comment]
Fixed

**Comment by tapishdongre** [comment]
You have magic in your hands
Thanks again

**Comment by bunnykek** [comment]
Bug reports are always welcome. Closing the issue.
