### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by csabu466** [bunnykek/kuku-dl#3]
Error opening input: Invalid argument

**Comment by bolavefasfas** [comment]
Not working Some other error 

```
Downloading Death Of A Legend
Death Of A Legend [WinError 2] The system cannot find the file specified
```
same error for all files but the png for album is getting downloaded the music files arent

**Comment by csabu466** [comment]
[Errno 2] No such file or directory:
same error for all files but the png for album is getting downloaded the music files arent

**Comment by bunnykek** [comment]
Just checked, everything is working fine. Make sure that you have active subscription.

**Comment by mathan7** [comment]
give step by step details on install
