### ISSUE TITLE
Is it working? 

### ISSUE THREAD

**Issue by rakib7676** [bunnykek/kuku-dl#6]
Hi! Is it working? I'm facing an issue. Can you help ? 
![image](https://github.com/bunnykek/kuku-dl/assets/158442736/6490fbd0-40b3-4436-b4e2-0efe0cd84170)

**Comment by tapishdongre** [comment]
![Kuku Error](https://github.com/user-attachments/assets/072be54b-35f5-4cfe-882c-c6b9f0719886)
Would need help, Am I exectuitng it propertly ? 
Installed FFMPEG 
Installed request, mutagen and bs4
Have full version of Kuku
Still getting this error 
Please help

**Comment by bunnykek** [comment]
Yeah, I will be fixing it soon.

**Comment by tapishdongre** [comment]
Just adding to my observed error, I did not use JWT Token, as I saw a comment "removed the requirement of JWT Token" but I was not sure if there is no token then how the URL will get access or how it will know that my account is logged in. Thanks
Also if possible in future a step by step instruciton or even a demo video link would really be helpful. Thanks agian for your hardwork in designing this code. Love form a desi sitting in Australia

**Comment by bunnykek** [comment]
I need a premium subscribed account browser cookies to test the premium functionality. For free episodes, its working now.

**Comment by bunnykek** [comment]
Fixed it. Try now. Still there is no need of any account.

**Comment by tapishdongre** [comment]
You are geneus, Yes it working. I wanted to know as it is fetching the first file available on m3u8 list, is it possible to fetch the 2nd or 3rd file. The 1st file is usually of a lower bitrate in this case 83kbps. 2nd and 3rd on streaming is 128 kbps or 320 kbps. I know how to downolad the episodes one by one, but your code is helpful to do it together and saves lot of time.
![kuku Part 2](https://github.com/user-attachments/assets/a0e8efe0-6cce-4484-8372-9ef04413a07d)

**Comment by tapishdongre** [comment]
Hope this image make woud add more insite
![Kuku Part 3](https://github.com/user-attachments/assets/7a6d24da-6b43-4c2b-865e-22adeefbb69c)

**Comment by tapishdongre** [comment]
![Kuku Part 4](https://github.com/user-attachments/assets/0c8149b6-4513-4d53-875d-82ae9d6d5636)

**Comment by tapishdongre** [comment]
Still I must say your code is awesome. If you can coordinate with someone knowing Visual Basic or Font end, you could build up a software that could incorporate this code and start the download with click of a button. (For less tech savy people who dont know how to install all python library and execute a code)

**Comment by tapishdongre** [comment]
Final Output
![kuku part 5](https://github.com/user-attachments/assets/5edec904-305f-407f-874e-d07151d0a8d2)

**Comment by tapishdongre** [comment]
Sent you a one time small gift of gratitude from my side. Hope you achive all your dreams in future. A huge thanks for all your hardwork.

**Comment by tapishdongre** [comment]
Bro Just discovered that the files with Subtitles are wroking fine, The one without subtitles gives this error. Is there a possibilty if I remove few lines of code while downloading these files where no such subtitles exist ? Example image attached. Otherwise code is excellet
![Error](https://github.com/user-attachments/assets/643d6968-b966-4d6d-9ccc-1bf4c781a641)

**Comment by bunnykek** [comment]
Fixed! Do git pull.

**Comment by tapishdongre** [comment]
That was so fast and so good. Better Sound Quality, Higher Bitrate and without Subtitles files are also able to download. Image attached. A very big thanks from my side. I have seen your other projects as well, you are doing so good for the community. Cheers
![Solved](https://github.com/user-attachments/assets/e39188c4-1771-4c97-96c9-e734172c43a7)
